import type { Config } from 'tailwindcss'

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    // Ensure all halal color classes are always included
    'bg-halal-orange',
    'bg-halal-orange-light',
    'bg-halal-orange-dark',
    'bg-halal-red',
    'bg-halal-red-light', 
    'bg-halal-red-dark',
    'bg-halal-green',
    'bg-halal-green-light',
    'bg-halal-green-dark',
    'bg-halal-brown',
    'bg-halal-brown-light',
    'bg-halal-brown-dark',
    'bg-halal-white',
    'bg-halal-cream',
    'bg-halal-gold',
    'text-halal-orange',
    'text-halal-orange-light',
    'text-halal-orange-dark',
    'text-halal-red',
    'text-halal-red-light',
    'text-halal-red-dark',
    'text-halal-green',
    'text-halal-green-light',
    'text-halal-green-dark',
    'text-halal-brown',
    'text-halal-brown-light',
    'text-halal-brown-dark',
    'text-halal-white',
    'text-halal-cream',
    'text-halal-gold',
    'border-halal-orange',
    'border-halal-red',
    'border-halal-green',
    'border-halal-gold',
    'hover:bg-halal-orange',
    'hover:bg-halal-orange-dark',
    'hover:bg-halal-red',
    'hover:bg-halal-green',
    'hover:bg-halal-green-dark',
    'hover:text-halal-orange',
    'hover:text-halal-red',
    'hover:text-halal-green',
    'hover:text-halal-gold',
    'from-halal-orange',
    'from-halal-green',
    'to-halal-red',
    'to-halal-green-light',
  ],
  theme: {
    extend: {
      colors: {
        'halal': {
          'orange': '#FF6B35',
          'orange-light': '#FF8C61',
          'orange-dark': '#E85A4F',
          'red': '#C73E1D',
          'red-light': '#D4532A',
          'red-dark': '#A72A0F',
          'green': '#2D8B47',
          'green-light': '#4CAF50',
          'green-dark': '#1B5E20',
          'brown': '#8D6E63',
          'brown-light': '#A1887F',
          'brown-dark': '#5D4037',
          'white': '#ffffff',
          'cream': '#FFF8F0',
          'gold': '#d4af37',
        }
      },
      fontFamily: {
        'sans': ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '100': '25rem',
        '112': '28rem',
        '128': '32rem',
      },
      borderRadius: {
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
    },
  },
  plugins: [],
} satisfies Config
